### PR TITLE
Jbogatay master

### PR DESCRIPTION
**Pull request by BeerK0in**
@jbogatay A few changes to your pull request and some additions.
I did not include the lat 10 trades in this version. We can think of something other like you mentioned in the other PR.

### CODE REVIEW

**Comment by jbogatay** [comment]
Nice.  I do like seeing the total profit even though I understand it's limitations.  Why did you remove it?

**Comment by jbogatay** [comment]
Maybe hide it behind a flag?

**Comment by BeerK0in** [comment]
It was killing small servers, because it parsed the whole logfile every 10sec for every pair.
I want to have a local store to only parse the whole log files once, and than just update that store.

**Comment by jbogatay** [comment]
I figured that would eventually be an issue.  I'm still a newb, my files are small.   I like the concept though, but storing the values externally (and dealing with all the side effects of that) is a pain in the ass.

**Comment by BeerK0in** [comment]
I'll try parsing the trade logs and subtracting the sells from the buys. Not sure if the result is the same as parsing the whole log file. But I'll give it a try.

**Comment by jbogatay** [comment]
I'm a bit busy at work, maybe I'll take a look later at reworking profit.   Something like this should work:
     
     cat poloniex-BTC_ETH-log.txt | grep Profit | awk '{s+=$4} END {print s}'

Could even stagger it so it runs every X cycles or something.

**Comment by jbogatay** [comment]
Here is a oneliner to get all profit from all pairs in gunbot directory.   Clean it up, map it into an array then it's pretty much ready for display again...    I'll see if I can polish it later but cat/grep should be pretty fast.

     for f in ~/gunbot/*-log.txt; do profit=`cat ${f} | grep Profit | awk '{s+=$4} END {print s}'`; echo "$f - $profit"; done;

**Comment by BeerK0in** [comment]
That will not run on widows servers :(

**Comment by BeerK0in** [comment]
But yes, it is very fast!

BTW: parsing the trades-logs and trying to calculate the profit with that numbers does not work. :(

**Comment by BeerK0in** [comment]
I'm going to spend half the day tomorrow to optimize the monitor. Profit is also a topic. I can add the also the flag if you can wait till tomorrow.

Archiving logs is no option since the profit info is in that logs. I'm going to try to get the profit from the trades-logs. There must be a way. 

Or profit is linux only. Would work for me ;)

**Comment by jbogatay** [comment]
I may even includ gunbot in my logrotate just to deal with it automatically.   But after typing my last post...  Hmmm daily profit/weekly profit columns might be more interesting....

**Comment by jbogatay** [comment]
Sweet.  I'll check it out.   I look at the profit as shown in monitor more as a guidepost -vs- accurate.

**Pull request merged**
